name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Mill
      uses: jodersky/setup-mill@v0.3.0
      with:
        mill-version: '1.0.6'
    - name: Compile
      run: mill custom.compile
    - name: Test
      run: mill custom.test