name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Mill
      run: |
        curl -fsSL -o mill https://raw.githubusercontent.com/com-lihaoyi/mill/1.0.6/mill
        chmod +x mill
        ./mill --version
    - name: Publish Local
      run: ./mill custom.publishLocal
    - name: Publish
      run: ./mill custom.publish