name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gvolpe/setup-mill@v2
      with:
        mill-version: "0.12.0"
    - run: mill custom.compile
    - run: mill custom.test