name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Mill
      run: |
        curl -L https://github.com/com-lihaoyi/mill/releases/download/1.0.6/1.0.6-assembly > mill
        chmod +x mill
    - name: Compile
      run: ./mill custom.compile
    - name: Test
      run: ./mill custom.test